[settings]
pin = true

[env]
MC_DISABLE_PAGER = "true"

[tools]
bitwarden = "2025.10.0"
chezmoi = "2.67.0"
cosign = "3.0.2"
jq = "1.8.1"
kubectl = "1.32.6"
mc = "2025-07-21T05-28-08Z"
usage = "2.5.1"
uv = "0.9.5"
yq = "4.48.1"
